export const SET_COUNTRIES = "SET_COUNTRIES";
export const SET_COUNTRIENAME = "SET_COUNTRIENAME"
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const FILTER_COUNTRY = "FILTER_COUNTRY";
export const ORDER_COUNTRY = "ORDER_COUNTRY";
